#!/usr/bin/perl -w
#
# Copyright (C) 2009-2011 Foswiki Contributors
#
# For licensing info read LICENSE file in the Foswiki root.
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details, published at 
# http://www.gnu.org/copyleft/gpl.html

# Set library paths in @INC, at compile time
BEGIN {
  if (-e './setlib.cfg') {
    unshift @INC, '.';
  } elsif (-e '../bin/setlib.cfg') {
    unshift @INC, '../bin';
  }
  require 'setlib.cfg';
}

use strict;
use Foswiki ();
use Foswiki::Contrib::Stringifier ();
use Cwd ();

my $fileName = $ARGV[0] ;
die "no filename" unless $fileName;
die "can't read $fileName" unless -r $fileName;

$fileName = Cwd::abs_path($fileName);

my $stringifier = new Foswiki::Contrib::Stringifier();
my $text = $stringifier->stringFor($fileName);
print $text."\n" if $text;

1;
